### ISSUE TITLE
Error While Inserting a new Code

### ISSUE THREAD

**Issue by OmerCD** [mustafarumeli/CodeLab#1]
Software gives error when I tried to Send a new code.
This is the error location. CodePieceCRUD class.
![error](https://user-images.githubusercontent.com/8603362/32139094-0ec00a74-bc49-11e7-9967-49c15c0df05a.PNG)
This is the error message.
![errormessage](https://user-images.githubusercontent.com/8603362/32139097-1d182962-bc49-11e7-9712-27c241d1a673.PNG)

**Comment by mustafarumeli** [comment]
I think it is about size of image you try to add to the database . It works fine on my side . So we should resize image before inserting database

**Comment by OmerCD** [comment]
Thinking that I haven't added any image, it is a problem.

**Comment by mustafarumeli** [comment]
Soo , we should make a validation about image ?  or image should be nullable ?

**Comment by mustafarumeli** [comment]
Fixed  by adding validation to adding image
